title: Axel Van Dyck
logo: /assets/img/github_circle.png
#logo: /assets/img/github_circle.png
description: ¡Hola! Te doy la bienvenida a mi quick scope de QA Tester.  
repository: https://github.com/avandyck16
show_downloads: false
#google_analytics: [Visit my GitHub Profile](https://github.com/avandyck16)
theme: jekyll-theme-minimal
