title: Axel Van Dyck
logo: /assets/img/github_circle.png
#logo: /assets/img/github_circle.png
description: ¡Hola! Bienvenido a mi portafolio de QA.<br>Listado de mis proyectos más relevantes documentados.<br>Al final encontrarás un proyecto histórico del 2011.<br><strong>QA Engineer | Test Automation & Manual Testing</strong>
repository: https://github.com/avandyck16
show_downloads: false
#google_analytics: [Visit my GitHub Profile](https://github.com/avandyck16)
theme: jekyll-theme-minimal
