title: Axel Van Dyck
logo: /assets/img/github_circle.png
#logo: /assets/img/github_circle.png
description: ¡Hola! Bienvenido a mi portafolio de QA.<br>Presento aquí los proyectos en los que he trabajado, completamente documentados, con su propio repositorio.<br>Cada uno cuenta con un case study detallado con métricas, desafíos técnicos, soluciones, snippets, y evidencia visual del resultado final.
repository: https://github.com/avandyck16
show_downloads: false
#google_analytics: [Visit my GitHub Profile](https://github.com/avandyck16)
theme: jekyll-theme-minimal
